spring:
  application:
    name: ${ACCOUNT_HOST}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${ACCOUNT_DB_NAME}
    username: ${ACCOUNT_DB_USER}
    password: ${ACCOUNT_DB_PASS}

server:
  port: ${ACCOUNT_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka

jwt:
  key: "0xCODE"
