spring:
  application:
    name: ${DISCOVERY_HOST}
  cloud:
    loadbalancer:
      ribbon:
        enable: false

eureka:
  instance:
    hostname: ${DISCOVERY_HOST}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: ${DISCOVERY_PORT}
