version: "3.7"
services:
  discovery-service:
    build: discovery
    image: discovery-image
    networks:
      - bus
    ports:
      - ${DISCOVERY_PORT}:${DISCOVERY_PORT}
    env_file: .env
  authentication-service:
    build: authentication
    image: authentication-image
    depends_on:
      - ${DISCOVERY_HOST}
    networks:
      - bus
    env_file: .env
  gateway-service:
    build: gateway
    image: gateway-image
    depends_on:
      - ${DISCOVERY_HOST}
    networks:
      - bus
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    env_file: .env
  account-service:
    build: account
    image: account-image
    depends_on:
      - ${DISCOVERY_HOST}
    networks:
      - bus
    env_file: .env
networks:
  bus:
#    driver: bridge
