spring:
  application:
    name: ${GATEWAY_HOST}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: ${GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka
