spring:
  application:
    name: ${AUTHENTICATION_HOST}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${AUTHENTICATION_DB_NAME}
    username: ${AUTHENTICATION_DB_USER}
    password: ${AUTHENTICATION_DB_PASS}
  flyway:
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-url: "http://localhost:8080/client/auth/oauth2/google"

server:
  port: ${AUTHENTICATION_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka

jwt:
  key: "0xCODE"
