spring:
  application:
    name: ${AUTHENTICATION_HOST}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: ${AUTHENTICATION_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka

jwt:
  key: "0xCODE"
