spring:
  application:
    name: ${AUTHENTICATION_HOST}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${AUTHENTICATION_DB_NAME}
    username: ${AUTHENTICATION_DB_USER}
    password: ${AUTHENTICATION_DB_PASS}

server:
  port: ${AUTHENTICATION_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka

jwt:
  key: "0xCODE"
